// Generated by vovk-cli v0.3.0-beta.0
import type { VovkFetcher } from 'vovk/fetcher';
import { createRPC } from 'vovk/create-rpc';
import { schema } from './schema';

import type { Controllers as Controllers0 } from '../../app/api/static/[[...vovk]]/route.ts';

export const OpenApiRPC = createRPC<
  Controllers0['OpenApiRPC'],
  typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never
>(schema, 'static', 'OpenApiRPC', import('vovk/fetcher'), { validateOnClient: import('vovk-ajv') });

export { schema };
