// Generated by vovk-cli v0.3.0-beta.0

import segment0 from './../../../.vovk-schema/static.json' with { type: 'json' };

const meta = {
  $schema: 'https://vovk.dev/api/schema/v3/meta.json',
  config: {
    libs: {},
    rootEntry: 'api',
    $schema: 'https://vovk.dev/api/schema/v3/config.json',
  },
};

const segments = {
  static: segment0,
};

export const schema = {
  $schema: 'https://vovk.dev/api/schema/v3/schema.json',
  segments,
  meta,
};
