version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /test
    schedule:
      interval: weekly
    groups:
      npm-test:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /packages/vovk-python
    schedule:
      interval: weekly
    groups:
      pip:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
