// Generated by vovk-cli v0.3.0-beta.0 at 2026-10-01T08:35:35.928Z

import segment0 from './../../.vovk-schema/root.json' with { type: 'json' };

import segment1 from './../../.vovk-schema/static.json' with { type: 'json' };

import meta from './../../.vovk-schema/_meta.json' with { type: 'json' };

const segments = {
  '': segment0,
  static: segment1,
};

export const schema = {
  $schema: 'https://vovk.dev/api/schema/v3/schema.json',
  segments,
  meta,
};
