// Generated by vovk-cli v0.3.0-beta.0
import type { VovkFetcher } from 'vovk/fetcher';
import { createRPC } from 'vovk/create-rpc';
import { schema } from './schema';

import type { Controllers as Controllers0 } from '../src/app/api/[[...vovk]]/route.ts';

import type { Controllers as Controllers1 } from '../src/app/api/static/[[...vovk]]/route.ts';

export const UserRPC = createRPC<
  Controllers0['UserRPC'],
  typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never
>(schema, '', 'UserRPC', import('vovk/fetcher'), {
  validateOnClient: undefined,
  apiRoot: 'https://hello-world.vovk.dev/api',
});

export const StreamRPC = createRPC<
  Controllers0['StreamRPC'],
  typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never
>(schema, '', 'StreamRPC', import('vovk/fetcher'), {
  validateOnClient: undefined,
  apiRoot: 'https://hello-world.vovk.dev/api',
});

export const OpenApiRPC = createRPC<
  Controllers1['OpenApiRPC'],
  typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never
>(schema, 'static', 'OpenApiRPC', import('vovk/fetcher'), {
  validateOnClient: undefined,
  apiRoot: 'https://hello-world.vovk.dev/api',
});

export { schema };
