import pluralize from 'pluralize';

// feel free to open a direct PR if you have more common terms to add
const terms = [
  ['entity', 'entities'],
  ['entry', 'entries'],
  ['regex', 'regexes'],
  ['index', 'indexes'],
  ['matrix', 'matrices'],
  ['axis', 'axes'],
  ['schema', 'schemata'],
  ['criterion', 'criteria'],
  ['datum', 'data'],
  ['formula', 'formulae'],
  ['appendix', 'appendices'],
  ['vertex', 'vertices'],
  ['leaf', 'leaves'],
  ['analysis', 'analyses'],
  ['thesis', 'theses'],
  ['hypothesis', 'hypotheses'],
  ['phenomenon', 'phenomena'],
  ['alumnus', 'alumni'],
  ['focus', 'foci'],
  ['medium', 'media'],
  ['bacterium', 'bacteria'],
  ['radius', 'radii'],
  ['genus', 'genera'],
  ['corpus', 'corpora'],
  ['locus', 'loci'],
  ['nucleus', 'nuclei'],
  ['fungus', 'fungi'],
  ['syllabus', 'syllabi'],
  ['cactus', 'cacti'],
  ['automaton', 'automata'],
  ['stimulus', 'stimuli'],
  ['parenthesis', 'parentheses'],
  ['ellipsis', 'ellipses'],
  ['diagnosis', 'diagnoses'],
  ['oasis', 'oases'],
  ['crisis', 'crises'],
  ['antenna', 'antennas'],
  ['chateau', 'chateaux'],
  ['tableau', 'tableaux'],
  ['penny', 'pence'],
  ['memorandum', 'memoranda'],
  ['erratum', 'errata'],
  ['curriculum', 'curricula'],
  ['millennium', 'millennia'],
  ['stratum', 'strata'],
  ['spectrum', 'spectra'],
  ['apex', 'apices'],
  ['vortex', 'vortices'],
  ['calf', 'calves'],
  ['loaf', 'loaves'],
  ['foot', 'feet'],
  ['tooth', 'teeth'],
  ['mouse', 'mice'],
  ['goose', 'geese'],
  ['child', 'children'],
  ['person', 'people'],
  ['man', 'men'],
  ['woman', 'women'],
  ['ox', 'oxen'],
  ['die', 'dice'],
  ['brother', 'brethren'],
  ['larva', 'larvae'],
  ['nebula', 'nebulae'],
  ['vertebra', 'vertebrae'],
  ['addendum', 'addenda'],
  ['aquarium', 'aquaria'],
  ['stadium', 'stadia'],
  ['maximum', 'maxima'],
  ['minimum', 'minima'],
  ['referendum', 'referenda'],
  ['forum', 'fora'],
  ['knife', 'knives'],
  ['wolf', 'wolves'],
  ['elf', 'elves'],
  ['half', 'halves'],
  ['scarf', 'scarves'],
];

// whole words only: a suffix rule for "ox" would turn "inbox" into "inboxen"
export function addCommonTerms() {
  for (const [singular, plural] of terms) {
    pluralize.addIrregularRule(singular, plural);
  }
}
