// stamped as the first line of every generated file that can hold a comment,
// the pruner relies on it to tell generated files from user files
export const GENERATED_BANNER_PREFIX = 'Generated by vovk-cli';
