import assert from 'node:assert';
import fs from 'node:fs/promises';
import path from 'node:path';
import { afterEach, beforeEach, describe, it } from 'node:test';
import { removeUnlistedDirectories } from '../../../dist/utils/remove-unlisted-directories.mjs';

const tmpDir = path.join(process.cwd(), 'tmp_remove_unlisted');

const BANNER = '// Generated by vovk-cli v0.0.0 at 2024-01-01T00:00:00.000Z';

async function write(files: string[], content: string) {
  for (const file of files) {
    const absolute = path.join(tmpDir, file);
    await fs.mkdir(path.dirname(absolute), { recursive: true });
    await fs.writeFile(absolute, content, 'utf-8');
  }
}

// files the generator wrote carry the banner as their first line
const writeFiles = (files: string[]) => write(files, `${BANNER}\n// content`);
// files a user wrote never carry it, even when the name collides with ours
const writeUserFiles = (files: string[]) => write(files, '// content');

const list = async () => (await fs.readdir(tmpDir)).sort();

beforeEach(async () => {
  await fs.rm(tmpDir, { recursive: true, force: true });
  await fs.mkdir(tmpDir, { recursive: true });
});

afterEach(async () => {
  await fs.rm(tmpDir, { recursive: true, force: true });
});

await describe('removeUnlistedDirectories', async () => {
  await it('Removes stale segment directories and keeps allowed ones', async () => {
    await writeFiles(['root/index.ts', 'foo/index.ts', 'stale/index.ts', 'bar/baz/index.ts']);

    const skipped = await removeUnlistedDirectories(tmpDir, ['root', 'foo', 'bar/baz'], ['index.ts']);

    assert.deepStrictEqual(await list(), ['bar', 'foo', 'root']);
    assert.deepStrictEqual(skipped, []);
  });

  await it('Removes a stale nested segment directory', async () => {
    await writeFiles(['foo/index.ts', 'bar/baz/index.ts']);

    const skipped = await removeUnlistedDirectories(tmpDir, ['foo'], ['index.ts']);

    assert.deepStrictEqual(await list(), ['foo']);
    assert.deepStrictEqual(skipped, []);
  });

  await it('Keeps directories that hold files the generator did not write', async () => {
    await writeFiles(['root/index.ts', 'components/Button.tsx', 'hooks/nested/use-thing.ts', 'stale/index.ts']);

    const skipped = await removeUnlistedDirectories(tmpDir, ['root'], ['index.ts']);

    assert.deepStrictEqual(await list(), ['components', 'hooks', 'root']);
    assert.deepStrictEqual(skipped.map((dir) => path.relative(tmpDir, dir)).sort(), ['components', 'hooks']);
  });

  await it('Treats [package_name] as a wildcard segment', async () => {
    await writeFiles(['stale/my_pkg/index.ts', 'user/my_pkg/notes.md']);

    const skipped = await removeUnlistedDirectories(tmpDir, [], ['[package_name]/index.ts']);

    assert.deepStrictEqual(await list(), ['user']);
    assert.deepStrictEqual(
      skipped.map((dir) => path.relative(tmpDir, dir)),
      ['user']
    );
  });

  await it('Removes everything unlisted when no generated paths are given', async () => {
    await writeFiles(['root/index.ts', 'components/Button.tsx']);

    const skipped = await removeUnlistedDirectories(tmpDir, ['root']);

    assert.deepStrictEqual(await list(), ['root']);
    assert.deepStrictEqual(skipped, []);
  });

  await it('Keeps a user file whose name collides with a generated one', async () => {
    await writeFiles(['root/index.ts']);
    await writeUserFiles(['shared/index.ts', 'lib/nested/index.ts']);

    const skipped = await removeUnlistedDirectories(tmpDir, ['root'], ['index.ts']);

    assert.deepStrictEqual(await list(), ['lib', 'root', 'shared']);
    assert.deepStrictEqual(skipped.map((dir) => path.relative(tmpDir, dir)).sort(), ['lib', 'shared']);
  });

  await it('Still prunes a stale segment directory holding generated json', async () => {
    await writeFiles(['stale/index.ts']);
    await write(['stale/schema.json'], '{"$schema":"https://vovk.dev/api/schema/v3/segment.json"}');

    const skipped = await removeUnlistedDirectories(tmpDir, [], ['index.ts', 'schema.json']);

    assert.deepStrictEqual(await list(), []);
    assert.deepStrictEqual(skipped, []);
  });
});
