# Generated by vovk-cli v0.0.1-beta.82 at 2026-01-13T06:59:58.599Z

from __future__ import annotations
from typing import Any, Dict, List, Literal, Optional, Set, TypedDict, Union, Tuple, Generator, BinaryIO # type: ignore
from .api_client import ApiClient, HttpException

HttpException = HttpException

client = ApiClient('https://hello-world.vovk.dev/api')
 
class UserRPC: 
    # UserRPC.update_user POST `https://hello-world.vovk.dev/api/users/{id}`
    class __UpdateUserBody_profile(TypedDict):
        """
        User profile object
        """
        name: str
        age: int
    class UpdateUserBody(TypedDict):
        """
        User data object
        """
        email: str
        profile: UserRPC.__UpdateUserBody_profile
    class UpdateUserQuery(TypedDict):
        """
        Query parameters
        """
        notify: Literal["email", "push", "none"]
    class UpdateUserParams(TypedDict):
        """
        Path parameters
        """
        id: str
    class UpdateUserOutput(TypedDict):
        """
        Response object
        """
        success: bool
        id: str
        notify: Literal["email", "push", "none"]
    @staticmethod
    def update_user(
        body: UpdateUserBody,
        query: UpdateUserQuery,
        params: UpdateUserParams,
        headers: Optional[Dict[str, str]] = None,
        api_root: Optional[str] = None,
        disable_client_validation: bool = False
    ) -> UpdateUserOutput:
        """ 
        No summary
        Body: User data object
        Query: Query parameters
        Returns: Response object
        """
        return client.request( # type: ignore
            segment_name='',
            rpc_name='UserRPC',
            handler_name='updateUser',
            body=body,
            query=query,
            params=params,
            headers=headers,
            api_root=api_root,
            disable_client_validation=disable_client_validation
        )
        
     
class StreamRPC: 
    # StreamRPC.stream_tokens GET `https://hello-world.vovk.dev/api/streams/tokens`
    class StreamTokensIteration(TypedDict):
        """
        Streamed token object
        """
        message: str
    @staticmethod
    def stream_tokens(

        headers: Optional[Dict[str, str]] = None,
        api_root: Optional[str] = None,
        disable_client_validation: bool = False
    ) -> Generator[StreamTokensIteration, None, None]:
        """ 
        No summary
        """
        return client.request( # type: ignore
            segment_name='',
            rpc_name='StreamRPC',
            handler_name='streamTokens',

            headers=headers,
            api_root=api_root,
            disable_client_validation=disable_client_validation
        )
        
    
 
class OpenApiRPC: 
    # OpenApiRPC.get_spec GET `https://hello-world.vovk.dev/api/static/openapi.json`

    @staticmethod
    def get_spec(

        headers: Optional[Dict[str, str]] = None,
        api_root: Optional[str] = None,
        disable_client_validation: bool = False
    ) -> Any:
        """ 
        No summary
        """
        return client.request( # type: ignore
            segment_name='static',
            rpc_name='OpenApiRPC',
            handler_name='getSpec',

            headers=headers,
            api_root=api_root,
            disable_client_validation=disable_client_validation
        )
        
    

