// auto-generated by vovk-cli v0.0.1-draft.300 at 2025-07-29T18:36:50.425Z

import meta from './../../../.vovk-schema/_meta.json' with { type: "json" };



const segments = {
  
};

export const schema = {
  $schema: 'https://vovk.dev/api/spec/v3/schema.json',
  segments,
  meta: {
    $schema: 'https://vovk.dev/api/spec/v3/meta.json',
    apiRoot: 'http://localhost:3000/api', // for debugging purposes
    
    ...meta,
    
  }
};

