// auto-generated by vovk-cli v0.0.1-draft.331 at 2025-08-17T17:09:58.831Z

import meta from './../../../.vovk-schema/_meta.json' with { type: 'json' };

const segments = {};

export const schema = {
  $schema: 'https://vovk.dev/api/schema/v3/schema.json',
  segments,
  meta: {
    $schema: 'https://vovk.dev/api/schema/v3/meta.json',
    apiRoot: 'http://localhost:3000/api', // for debugging purposes

    ...meta,
  },
};
