// auto-generated by Vovk.ts 2025-05-29T15:21:21.842Z
import meta from './../../../.vovk-schema/_meta.json' with { type: "json" };

const segments = {
};

export const schema = {
  $schema: 'https://vovk.dev/api/spec/v3/schema.json',
  segments,
  meta: {
    apiRoot: 'http://localhost:3001/api',
    ...meta,
  }
};