// auto-generated by Vovk.ts 2025-05-30T15:32:50.830Z

import meta from './../../../../.vovk-schema/_meta.json' with { type: 'json' };

import segment0 from './../../../../.vovk-schema/foo/client.json' with { type: 'json' };

const segments = {
  'foo/client': segment0,
};

export const schema = {
  $schema: 'https://vovk.dev/api/spec/v3/schema.json',
  segments,
  meta: {
    apiRoot: 'http://localhost:3000/api', // for debugging purposes
    ...meta,
  },
};
