// auto-generated by Vovk.ts 2025-06-11T10:36:04.466Z

import meta from './../../../../.vovk-schema/_meta.json' with { type: "json" };

import segment0 from './../../../../.vovk-schema/foo/client.json' with { type: "json" };

const segments = {
  'foo/client': segment0,
};

export const schema = {
  $schema: 'https://vovk.dev/api/spec/v3/schema.json',
  segments,
  meta: {
    apiRoot: 'http://localhost:3210/api', // for debugging purposes
    ...meta,
  }
};
