import { createVovkApp } from './createVovkApp';
import {
  HttpStatus,
  HttpMethod,
  VovkSchemaIdEnum,
  type KnownAny,
  type VovkErrorResponse,
  type VovkRequest,
  type VovkBody,
  type VovkQuery,
  type VovkParams,
  type VovkReturnType,
  type VovkYieldType,
  type VovkOutput,
  type VovkIteration,
  type VovkMetaSchema,
  type VovkSegmentSchema,
  type VovkControllerSchema,
  type VovkHandlerSchema,
  type VovkSchema,
  type VovkConfig,
  type VovkGeneratorConfig,
  type VovkReadmeConfig,
  type VovkSamplesConfig,
  type VovkOpenAPIMixin,
  type VovkOpenAPIMixinNormalized,
  type VovkStrictConfig,
  type VovkValidationType,
  type VovkLLMTool,
  type VovkTypedMethod,
  type VovkBasicJSONSchema,
  type VovkOperationObject,
} from './types';
import {
  type VovkRPCModule,
  type VovkFetcher,
  type VovkFetcherOptions,
  type VovkValidateOnClient,
  type VovkStreamAsyncIterable,
  createRPC,
  fetcher,
  createFetcher,
  progressive,
} from './client';
import { operation, openAPIToVovkSchema, vovkSchemaToOpenAPI } from './openapi';
import { HttpException } from './HttpException';
import { createDecorator } from './utils/createDecorator';
import { JSONLinesResponse } from './JSONLinesResponse';
import { generateStaticAPI } from './utils/generateStaticAPI';
import { withValidationLibrary } from './utils/withValidationLibrary';
import { createStandardValidation } from './utils/createStandardValidation';
import { multitenant } from './utils/multitenant';
import { createLLMTools } from './utils/createLLMTools';
import { createCodeSamples } from './utils/createCodeSamples';
import { createValidateOnClient } from './utils/createValidateOnClient';
import { resolveGeneratorConfigValues } from './utils/resolveGeneratorConfigValues';

export {
  type KnownAny,
  type VovkRPCModule,
  type VovkFetcher,
  type VovkFetcherOptions,
  type VovkStreamAsyncIterable,
  type VovkValidateOnClient,
  type VovkSegmentSchema,
  type VovkErrorResponse,
  type VovkRequest,
  type VovkOutput,
  type VovkIteration,
  type VovkBody,
  type VovkQuery,
  type VovkParams,
  type VovkYieldType,
  type VovkReturnType,
  type VovkMetaSchema,
  type VovkControllerSchema,
  type VovkHandlerSchema,
  type VovkSchema,
  type VovkConfig,
  type VovkStrictConfig,
  type VovkGeneratorConfig,
  type VovkReadmeConfig,
  type VovkSamplesConfig,
  type VovkOpenAPIMixin,
  type VovkOpenAPIMixinNormalized,
  type VovkValidationType,
  type VovkLLMTool,
  type VovkTypedMethod,
  type VovkBasicJSONSchema,
  type VovkOperationObject,
  VovkSchemaIdEnum,
  JSONLinesResponse,
  HttpException,
  HttpStatus,
  HttpMethod,
  createVovkApp,
  createDecorator,
  createRPC,
  fetcher,
  createFetcher,
  generateStaticAPI,
  withValidationLibrary,
  createStandardValidation,
  multitenant,
  createLLMTools,
  createCodeSamples,
  createValidateOnClient,
  progressive,
  operation,
  openAPIToVovkSchema,
  vovkSchemaToOpenAPI,
  resolveGeneratorConfigValues,
};

export const { get, post, put, patch, del, head, options, prefix, initSegment } = createVovkApp();
