import { createVovkApp } from './createVovkApp';
import {
  HttpStatus as HttpStatus,
  HttpMethod as HttpMethod,
  type KnownAny,
  type VovkErrorResponse,
  type VovkRequest,
  type VovkBody,
  type VovkQuery,
  type VovkParams,
  type VovkReturnType,
  type VovkYieldType,
  type VovkControllerBody,
  type VovkControllerQuery,
  type VovkControllerParams,
  type VovkControllerYieldType,
  type VovkControllerOutput,
  type VovkSegmentSchema,
  type VovkControllerSchema,
  type VovkHandlerSchema,
  type VovkFullSchema,
  type VovkConfig,
  type VovkStrictConfig,
  type VovkEnv,
  type VovkValidationType,
} from './types';
import {
  type VovkClient,
  type VovkClientOptions,
  type VovkClientFetcher,
  type VovkDefaultFetcherOptions,
  type VovkValidateOnClient,
  type VovkStreamAsyncIterable,
  createRPC,
  fetcher,
} from './client';
import { HttpException } from './HttpException';
import { createDecorator } from './createDecorator';
import { JSONLinesResponse } from './StreamJSONResponse';
import { generateStaticAPI } from './utils/generateStaticAPI';
import { withValidation } from './utils/withValidation';

export {
  type KnownAny,
  type VovkClient,
  type VovkClientFetcher,
  type VovkDefaultFetcherOptions,
  type VovkStreamAsyncIterable,
  type VovkValidateOnClient,
  type VovkSegmentSchema,
  type VovkErrorResponse,
  type VovkRequest,
  type VovkControllerBody,
  type VovkControllerQuery,
  type VovkControllerParams,
  type VovkControllerYieldType,
  type VovkControllerOutput,
  type VovkBody,
  type VovkQuery,
  type VovkParams,
  type VovkYieldType,
  type VovkReturnType,
  type VovkClientOptions,
  type VovkControllerSchema,
  type VovkHandlerSchema,
  type VovkFullSchema,
  type VovkConfig,
  type VovkStrictConfig,
  type VovkEnv,
  type VovkValidationType,
  JSONLinesResponse,
  HttpException,
  HttpStatus,
  HttpMethod,
  createVovkApp,
  createDecorator,
  createRPC,
  fetcher,
  generateStaticAPI,
  withValidation,
};

export const { get, post, put, patch, del, head, options, prefix, initVovk } = createVovkApp();
